# Config file for Jekyll serving. This just points it at the docs constructed by Sphinx, because
# Sphinx can do fancy things like autogenerating docs from docstrings.
baseurl: /pyppin
source: docs
include:
  - /_static
  - /_images
